source: src
paths:
  uploads: public/uploads
  static: public
  collections: ''
  data: data
  layouts:
collections_config:
  data:
    path: src/data
_enabled_editors:
  - visual
  - content
  - data
timezone: EST
