source: src
paths:
  uploads: public/uploads
  static: public
  collections: ''
  data: data
  layouts:
collections_config:
  data:
    path: data
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_enabled_editors:
  - visual
  - content
  - data
_inputs:
  blob1:
    type: textarea
    cascade: true
  blob2:
    type: textarea
    cascade: true
  image1:
    type: image
    cascade: true
  image2:
    type: image
    cascade: true
timezone: EST
